BEGIN;
CREATE DATABASE IF NOT EXISTS QnADB;

USE QnADB;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS answer;

CREATE TABLE users (
	uid NUMERIC(13) NOT NULL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	password CHAR(32) NOT NULL,
	privilege VARCHAR(5)
	CHECK (privilge IN ('admin', 'user', 'guest')),
	avatar BLOB
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE question (
	qid NUMERIC(10) NOT NULL PRIMARY KEY,
	content VARCHAR(200) NOT NULL,
	uid NUMERIC(13) NOT NULL,
	uploadtime TIMESTAMP NOT NULL,
	FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE answer (
	qid NUMERIC(10) NOT NULL,
	uid NUMERIC(13) NOT NULL,
	content TEXT NOT NULL,
	FOREIGN KEY (uid) REFERENCES users(uid) ON DELETE RESTRICT,
	FOREIGN KEY (qid) REFERENCES question(qid) ON DELETE CASCADE,
	PRIMARY KEY(qid, uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

COMMIT;